<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Valentine's Day Partner Reveal</title>
    <style>
        body {
            margin: 0;
            padding: 0;
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
            background-color: #000;
            overflow: hidden;
        }

        /* Space Background with Twinkling Stars */
        .space {
            position: absolute;
            width: 100%;
            height: 100%;
            background: radial-gradient(circle, #000 20%, #111 80%);
            overflow: hidden;
        }

        .star {
            position: absolute;
            width: 2px;
            height: 2px;
            background: white;
            border-radius: 50%;
            animation: twinkle 2s infinite ease-in-out;
        }

        @keyframes twinkle {
            0%, 100% {
                opacity: 0;
            }
            50% {
                opacity: 1;
            }
        }

        /* Valentine's Day Partner Reveal Text Animation */
        .reveal-text {
            position: absolute;
            font-size: 48px;
            font-family: 'Arial', sans-serif;
            font-weight: bold;
            color: white;
            text-shadow: 0 0 10px white, 0 0 20px white, 0 0 30px white;
            opacity: 0;
            animation: reveal 3s ease-in-out forwards;
        }

        @keyframes reveal {
            0% {
                opacity: 0;
                transform: scale(0.8);
            }
            50% {
                opacity: 1;
                transform: scale(1.2);
            }
            100% {
                opacity: 0;
                transform: scale(0.8);
            }
        }

        /* Heart and Names Container */
        .container {
            position: relative;
            display: flex;
            align-items: center;
            justify-content: center;
            opacity: 0;
            animation: appear 2s 3s forwards;
        }

        /* Heart Animation */
        .heart {
            position: relative;
            width: 150px; /* Bigger heart */
            height: 135px; /* Bigger heart */
            filter: blur(10px);
            animation: unblur 1.3s 5s forwards; /* Unblur after 1.3 seconds */
        }

        .heart::before,
        .heart::after {
            content: '';
            position: absolute;
            top: 0;
            width: 78px; /* Adjusted for bigger heart */
            height: 120px; /* Adjusted for bigger heart */
            background: #ff4757;
            border-radius: 50px 50px 0 0;
        }

        .heart::before {
            left: 75px; /* Adjusted for bigger heart */
            transform: rotate(-45deg);
            transform-origin: 0 100%;
        }

        .heart::after {
            left: 0;
            transform: rotate(45deg);
            transform-origin: 100% 100%;
        }

        /* Names Animation */
        .name {
            position: absolute;
            font-size: 36px; /* Bigger names */
            font-family: 'Arial', sans-serif;
            color: white;
            filter: blur(10px);
            animation: unblur 1.3s 5s forwards, glow 2s infinite alternate; /* Unblur and glow */
        }

        .name.left {
            left: -180px; /* Adjusted for bigger names */
        }

        .name.right {
            right: -180px; /* Adjusted for bigger names */
        }

        @keyframes appear {
            0% {
                opacity: 0;
                transform: scale(0.5);
            }
            100% {
                opacity: 1;
                transform: scale(1);
            }
        }

        @keyframes unblur {
            0% {
                filter: blur(10px);
            }
            100% {
                filter: blur(0);
            }
        }

        @keyframes glow {
            0% {
                text-shadow: 0 0 5px white, 0 0 10px white, 0 0 20px white;
                transform: scale(1);
            }
            100% {
                text-shadow: 0 0 10px white, 0 0 20px white, 0 0 30px white;
                transform: scale(1.1);
            }
        }

        /* Firecracker Animation */
        .firecracker {
            position: absolute;
            width: 5px;
            height: 5px;
            background: #ffdd59;
            border-radius: 50%;
            animation: explode 1s ease-out;
        }

        @keyframes explode {
            0% {
                transform: scale(0);
                opacity: 1;
            }
            100% {
                transform: scale(10);
                opacity: 0;
            }
        }
    </style>
</head>
<body>
    <div class="space" id="space"></div>
    <div class="reveal-text">Valentine's Day Partner Reveal</div>
    <div class="container">
        <div class="name left">Parasar</div>
        <div class="heart" id="heart"></div>
        <div class="name right">Thiti</div>
    </div>

    <script>
        // Create Twinkling Stars
        const space = document.getElementById('space');
        for (let i = 0; i < 200; i++) {
            const star = document.createElement('div');
            star.classList.add('star');
            star.style.top = `${Math.random() * 100}%`;
            star.style.left = `${Math.random() * 100}%`;
            star.style.animationDelay = `${Math.random() * 2}s`;
            space.appendChild(star);
        }

        // Firecracker Animation
        function createFirecracker() {
            const firecracker = document.createElement('div');
            firecracker.classList.add('firecracker');
            firecracker.style.top = `${Math.random() * 80 + 10}%`;
            firecracker.style.left = `${Math.random() * 80 + 10}%`;
            document.body.appendChild(firecracker);

            setTimeout(() => {
                firecracker.remove();
            }, 1000);
        }

        // Trigger Firecrackers After Heart Appears
        setTimeout(() => {
            setInterval(createFirecracker, 200);
        }, 5000); // Firecrackers start after 5 seconds
    </script>
</body>
</html>
